import type { Metadata } from 'next'
import { Nanum_Gothic } from 'next/font/google'
import './globals.css'
import { ClerkProvider } from '@clerk/nextjs'

const naum = Nanum_Gothic({
  weight: '400',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Drive_APP',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <ClerkProvider>
      <html lang="en">
        <body className={naum.className}>{children}</body>
      </html>
    </ClerkProvider>
  )
}
